/* Generated by Together */

package com.neocoders.vglviewer.vglDocument;

/** Defines metrics that can be got on a VGLFont
*/
public interface AbstractVGLFontMetrics {
    public int getHeight();

    public int getLeading();

    public int getMaxAscent();

    public int stringWidth(String str);
}
