/* Generated by Together */

package com.neocoders.vglviewer.vglDocument;

/** Defines a VGLFont factory which can also supply VGLFontMetrics on VGLFonts which it has created. */
public interface AbstractVGLFontFactory {
    /** Get a new VGLFont to given specifications */
    public VGLFont newFont(String family, int style, int size);

    /**
     * @supplierCardinality 0..*
     * @clientCardinality 1
     * @label newFont
     */
    /*# VGLFont lnkVGLFont; */
}
