/* Generated by Together */

package com.neocoders.vglviewer.vglDocument;

/** A VGL color as red, green and blue values in the range [0..255]. */
public class VGLColor {
    /** Initialise a VGL color */
    public VGLColor(int red, int green, int blue) {
        this.red = red;
        this.green = green;
        this.blue = blue;
    }

    public int red;
    public int green;
    public int blue;
}
