/* Generated by Together */

package com.neocoders.vglviewer.vglDocument;

public class VGLPoints {
    public VGLPoints(long[] sx, long[] sy) {
        this.sx = sx;
        this.sy = sy;
    }

    public long[] getSX() {
        return sx;
    }

    public long[] getSY() {
        return sy;
    }

    private long[] sx;
    private long[] sy;
}
