/* Generated by Together */

package com.neocoders.sdaz;

public class SDAZPoint {
    public int x;
    public int y;

    public SDAZPoint(int x, int y) {
        this.x = x;
        this.y = y;
    }
}
