/* Generated by Together */

package vglDocument;

/** An abstract VGL element visitor; implement this to define operations to apply to VGL document elements */
public interface VGLElementVisitor {
    /** Visit a VGL polygon element */
    public void visitPolygon(VGLPolygon polygon);

    /** Visit a VGL path element */
    public void visitPath(VGLPath path);

    /** Visit a VGL circle element */
    public void visitCircle(VGLCircle circle);

    /** Visit a VGL text element */
    public void visitText(VGLText text);

    /**
     * @clientRole visits elements of 
     */
    /*# VGLDocument lnkDocument; */
}
