/* Generated by Together */

package vglDocument;

/** A VGL text font */
public class VGLFont {
    /**
     * @clientCardinality 1
     * @supplierCardinality 1
     * @supplierRole metrics*/
    private AbstractVGLFontMetrics metrics;
    private String family;
    private int size;
    private int style;

    /**
     *Initialise new font
     * @param metrics my font metrics
     * @param family  font family, eg. "Helvetica"
     * @param style font style, 0 - normal, 1 - bold, 2- italic
     * @param size in pixels
     */
    public VGLFont(AbstractVGLFontMetrics metrics, String family, int style, int size) {
        this.metrics = metrics;
        this.family = family;
        this.style = style;
        this.size = size;
    }

    /** Get family of font */
    public String getFamily() {
        return family;
    }

    /** Get size of font in pixels */
    public int getSize() {
        return size;
    }

    /**
     * Get style of font
     * @return 0 - normal, 1 - bold, 2 - italic
     */
    public int getStyle() {
        return style;
    }

    /** Get some metrics on this font */
    public AbstractVGLFontMetrics getMetrics() {
        return metrics;
    }
}
