/* Generated by Together */

package vglDocument;

public class VGLStyle {
	public VGLStyle(VGLColor fillColor, VGLColor strokeColor, VGLFont font) {
		this.fillColor = fillColor;
		this.strokeColor = strokeColor;
		this.font = font;
	}

	/** Get fill color */
	public VGLColor getFillColor() {
		return fillColor;
	}

	/** Get stroke color */
	public VGLColor getStrokeColor() {
		return strokeColor;
	}

	/** Get font */
	public VGLFont getFont() {
		return font;
	}

	private VGLColor fillColor;

	/**
	 * @clientCardinality 1
	 * @supplierCardinality 1
	 * @supplierRole strokeColor
	 */
	private VGLColor strokeColor;

	/**
	 * @clientCardinality 1
	 * @supplierCardinality 1
	 * @supplierRole font
	 */
	private VGLFont font;

}
