/* Generated by Together */

package vglViewer;

import vglDocument.VGLFont;
import vglDocument.AbstractVGLFontMetrics;
import vglDocument.AbstractVGLFontFactory;
import java.util.Map;
import java.awt.Font;
import java.util.HashMap;
import java.awt.FontMetrics;
import java.awt.Component;

/**
 * Creates VGLFonts
 */
public class AWT_VGLFontFactory implements AbstractVGLFontFactory {
    /** Create new factory */
    public AWT_VGLFontFactory(Component component) {
        this.myAWTComponent = component;

    }

    /** Create new VGLFont */
    public VGLFont newFont(String family, int style, int size) {
        Font awtFont = new Font(family, style, size);
    	FontMetrics awtFontMetrics = myAWTComponent.getFontMetrics(awtFont);
        AbstractVGLFontMetrics metrics = new AWT_VGLFontMetrics(awtFontMetrics);
        VGLFont vglFont = new VGLFont(metrics, family, style, size);
        return vglFont;
    }

    private Component myAWTComponent;
}
