/* Generated by Together */

package vglViewer;

import java.awt.FontMetrics;
import vglDocument.AbstractVGLFontMetrics;

/**
 * A bunch of metrics on some particular VGLFont; wraps an AWT FontMetrics to do the job of computing the
 * various metrics when asked for
 */
public class AWT_VGLFontMetrics implements AbstractVGLFontMetrics {
    /** Create new metrics with AWT FontMetrics to wrap */
    public AWT_VGLFontMetrics(FontMetrics fontMetrics) {
        this.fontMetrics = fontMetrics;
    }

    public int getHeight() {
        return fontMetrics.getHeight();
    }

    public int getLeading() {
        return fontMetrics.getLeading();
    }

    public int getMaxAscent() {
        return fontMetrics.getMaxAscent();
    }

    public int stringWidth(String str) {
        return fontMetrics.stringWidth(str);
    }

    private FontMetrics fontMetrics;
}
