/* Generated by Together */

package vglViewer;

import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import sdaz.SDAZDriver;
import java.awt.event.MouseEvent;
import sdaz.SDAZPoint;
import java.awt.Point;

public interface MouseHandler extends MouseMotionListener, MouseListener {
}
