/* Generated by Together */

package docViewPanel;

import java.awt.Graphics;
import java.awt.Color;

class SDAZIndicator {
    public void update(int xOrigin, int yOrigin, int xOffset, int yOffset, int width, int height) {
        this.xOrigin = xOrigin;
        this.yOrigin = yOrigin;
        this.xOffset = xOffset;
        this.yOffset = yOffset;
        this.width = width;
        this.height = height;
    }

    public void render(Graphics g) {
      
        g.setColor(new Color(255, 0, 0));
        g.drawLine(xOrigin, yOrigin, xOffset, yOffset);
        int xmin = (xOffset) - (width / 2);
        int ymin = (yOffset) - (height / 2);
        g.drawRect(xmin, ymin, width, height);
        g.drawRect(xmin-1, ymin-1, width+2, height+2);
        g.setColor(new Color(0, 0, 0));
        g.fillOval(xOrigin-5, yOrigin-5, 10,10);
       g.setColor(new Color(255, 0, 0));
        g.fillOval(xOffset-5, yOffset-5, 10,10);
    }

    private int xOrigin;
    private int yOrigin;
    private int xOffset;
    private int yOffset;
    private int width;
    private int height;
}
