/* Generated by Together */

package com.neocoders.vglviewer.sdaz;

public class SDAZViewport {
    public long xmin;
    public long ymin;
    public long xmax;
    public long ymax;

    public SDAZViewport() {
        this.xmin = 0L;
        this.ymin = 0L;
        this.xmax = 0L;
        this.ymax = 0L;
    }

    public SDAZViewport(SDAZViewport v) {
        this.xmin = v.xmin;
        this.ymin = v.ymin;
        this.xmax = v.xmax;
        this.ymax = v.ymax;
    }

    public SDAZViewport(long xmin, long ymin, long xmax, long ymax) {
        this.xmin = xmin;
        this.ymin = ymin;
        this.xmax = xmax;
        this.ymax = ymax;
    }
}
