/* Generated by Together */

package com.neocoders.vglviewer.docViewPanel;

import java.awt.Graphics;
import com.neocoders.vglviewer.vglDocument.VGLColor;
import com.neocoders.vglviewer.vglRenderer.VGLRenderingStrategy;
import java.awt.Font;

/** Adapts an AWT Graphics context object to a map renderer GraphicsContext */
class AWTRenderingStrategy implements VGLRenderingStrategy {
    private Graphics g;

    public AWTRenderingStrategy(Graphics g) {
        this.g = g;
    }

    public void setColor(VGLColor c) {
        g.setColor(new java.awt.Color(c.red, c.green, c.blue));
    }

    public void fillPolygon(int[] sx, int[] sy, int n) {
        g.fillPolygon(sx, sy, n);
    }

    public void drawPolygon(int[] sx, int[] sy, int n) {
        g.drawPolygon(sx, sy, n);
    }

    public void drawPath(int[] sx, int[] sy, int n) {
        g.drawPolyline(sx, sy, n);
    }

    public void fillOval(int x, int y, int width, int height) {
        g.fillOval(x, y, width, height);
    }

    public void drawOval(int x, int y, int width, int height) {
        g.drawOval(x, y, width, height);
    }

    public void drawLine(int x1, int y1, int x2, int y2) {
        g.drawLine(x1, y1, x2, y2);
    }

    public void setFont(String family, int style, int size) {
        g.setFont(new Font(family, style, size));
    }

    public void drawString(String value, int x, int y) {
        g.drawString(value, x, y);
    }
}
