package com.neocoders.vglviewer.docViewPanel;

import java.awt.Graphics;
import java.awt.LayoutManager;
import java.awt.Panel;
import java.awt.Image;

/* Generated by Together */

class DoubleBufferedPanel extends Panel {
    private int bufferWidth;
    private int bufferHeight;
    private Image bufferImage;
    private Graphics bufferGraphics;

    public DoubleBufferedPanel() {
        super();
    }

    public DoubleBufferedPanel(LayoutManager layout) {
        super(layout);
    }

    public void update(Graphics g) {
        paint(g);
    }

    public void paint(Graphics g) {
        if (bufferWidth != this.getWidth() || bufferHeight != this.getHeight() || bufferImage == null ||
            bufferGraphics == null) {
                resetBuffer();
        }
        if (bufferGraphics != null) {
            bufferGraphics.clearRect(0, 0, bufferWidth, bufferHeight);
            paintBuffer(bufferGraphics);
            g.drawImage(bufferImage, 0, 0, this);
        }
    }

    /** Override this to do the actual rendering */
    public void paintBuffer(Graphics g) {
    }

    private void resetBuffer() {
        bufferWidth = this.getWidth();
        bufferHeight = this.getHeight();
        if (bufferGraphics != null) {
            bufferGraphics.dispose();
            bufferGraphics = null;
        }
        if (bufferImage != null) {
            bufferImage.flush();
            bufferImage = null;
        }
        System.gc();
        bufferImage = this.createImage(bufferWidth, bufferHeight);
        bufferGraphics = bufferImage.getGraphics();
    }
}
