/* Generated by Together */

package sdaz;

public class SDAZWindow {
    public int xmin;
    public int ymin;
    public int xmax;
    public int ymax;

    public SDAZWindow() {
        this.xmin = 0;
        this.ymin = 0;
        this.xmax = 0;
        this.ymax = 0;
    }

    public SDAZWindow(int xmin, int ymin, int xmax, int ymax) {
        this.xmin = xmin;
        this.ymin = ymin;
        this.xmax = xmax;
        this.ymax = ymax;
    }
}
