/* Generated by Together */

package vglRenderer;

public class VGLWindow {
    public int xmin;
    public int ymin;
    public int xmax;
    public int ymax;

    public VGLWindow() {
        this.xmin = 0;
        this.ymin = 0;
        this.xmax = 100;
        this.ymax = 100;
    }

    public VGLWindow(int xmin, int ymin, int xmax, int ymax) {
        this.xmin = xmin;
        this.ymin = ymin;
        this.xmax = xmax;
        this.ymax = ymax;
    }

    public VGLWindow(VGLWindow w) {
        this(w.xmin, w.ymin,  w.xmax, w.ymax);
    }
}
