/* Generated by Together */

package vglDocument;

public class VGLPoint {
    public long x;
    public long y;

    public VGLPoint(long x, long y) {
        this.x = x;
        this.y = y;
    }
}
