/* Generated by Together */

package com.neocoders.vglviewer.vglDocument.utils;

import java.util.Map;
import java.util.HashMap;
import com.neocoders.vglviewer.vglDocument.VGLStyle;
import com.neocoders.vglviewer.vglDocument.VGLDocument;
import com.neocoders.vglviewer.vglDocument.VGLFont;
import com.neocoders.vglviewer.vglDocument.VGLColor;
import com.neocoders.vglviewer.vglDocument.AbstractVGLFontFactory;

/** A bunch of things that are useful during the VGLDocument building process */
class BuildContext {
    /** Create new builder context for a document to build, with an error handler to mop up errors */
    public BuildContext(VGLDocument document, ErrorHandler errorHandler, AbstractVGLFontFactory fontManager) {
        this.document = document;
        this.errorHandler = errorHandler;
        this.fontManager = fontManager;
        this.defaultFillColor = new VGLColor(255, 255, 255);
        this.defaultStrokeColor = new VGLColor(0, 0, 0);
        this.defaultFont = fontManager.newFont("Helvetica", 0, 12);
        this.defaultStyle = new VGLStyle(this.defaultFillColor, this.defaultStrokeColor, defaultFont);
        styleMap = new HashMap();
        id = 0;
    }

    /** Get the document being built */
    public VGLDocument getDocument() {
        return document;
    }

    /** Get error handler */
    public ErrorHandler getErrorHandler() {
        return this.errorHandler;
    }

    /** Get font manager; will be null if none set for this context */
    public AbstractVGLFontFactory getFontFactory() {
        return this.fontManager;
    }

    /** Associate style with given name */
    public void putStyle(String name, VGLStyle style) {
        styleMap.put(name, style);
    }

    /** Get style that was associated with given name earlier during build process */
    public VGLStyle getStyle(String name) {
        return (VGLStyle)styleMap.get(name);
    }

    /** Get default style, with white fillcolour, black stroke colour, and helvetica 12-point normal-style font */
    public VGLStyle getDefaultStyle() {
        return this.defaultStyle;
    }

    /** Get default fill color, which is white */
    public VGLColor getDefaultFillColor() {
        return this.defaultFillColor;
    }

    /** Get default stroke color, which is black */
    public VGLColor getDefaultStrokeColor() {
        return this.defaultStrokeColor;
    }

    /** Get default font, which is helvetica, normal-style, 12pt */
    public VGLFont getDefaultFont() {
        return this.defaultFont;
    }

    /** Get an ID that is unique within the build process */
    public String getID() {
        return Integer.toString(id++);
    }

    private Map styleMap;
    private VGLDocument document;

    /**
     * @supplierCardinality 1
     * @clientCardinality 1 
     */
    private ErrorHandler errorHandler;
    private AbstractVGLFontFactory fontManager;
    private int id;
    private VGLFont defaultFont;
    private VGLColor defaultFillColor;
    private VGLColor defaultStrokeColor;
    private VGLStyle defaultStyle;
}
