/* Generated by Together */

package com.neocoders.vglviewer.vglViewer;

import java.awt.event.MouseEvent;
import java.awt.Point;
import com.neocoders.vglviewer.vglRenderer.VGLWindow;
import com.neocoders.vglviewer.vglRenderer.VGLViewport;
import com.neocoders.vglviewer.docViewPanel.DocViewPanel;


public class ListeningForMarqueeMouse implements MouseHandler {
    public ListeningForMarqueeMouse(DocViewPanel docViewPanel) {
        this.docViewPanel = docViewPanel;
        this.downPoint = null;
        this.dragPoint = null;
        this.upPoint = null;
    }

    public void mousePressed(MouseEvent e) {
        downPoint = e.getPoint();
       
    }

    public void mouseReleased(MouseEvent e) {
        upPoint = e.getPoint();
        if (downPoint != null) {
            VGLWindow marquee = createMarquee(this.downPoint, this.upPoint);
            docViewPanel.zoomInto(marquee);
        }
    }

    public void mouseMoved(MouseEvent e) {

    }

    public void mouseDown(MouseEvent e) {

    }

    public void mouseUp(MouseEvent e) {

        /*
        upPoint = e.getPoint();
        if (downPoint != null) {
            VGLWindow marquee = createMarquee(this.downPoint, this.upPoint);
            com.neocoders.vglviewer.docViewPanel.zoomInto(marquee);
        }
        */
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }

    public void mouseClicked(MouseEvent e) {
        //   com.neocoders.vglviewer.docViewPanel.setMarquee(null);
    }

    public void mouseDragged(MouseEvent e) {
        dragPoint = e.getPoint();
        VGLWindow marquee = createMarquee(this.downPoint, this.dragPoint);
        docViewPanel.setMarquee(marquee);
    }

    private VGLWindow createMarquee(Point a, Point b) {
        int xmin;
        int ymin;
        int xmax;
        int ymax;
        if (a.x < b.x) {
            xmin = a.x;
            xmax = b.x;
        }
        else {
            xmin = b.x;
            xmax = a.x;
        }
        if (a.y < b.y) {
            ymin = a.y;
            ymax = b.y;
        }
        else {
            ymin = b.y;
            ymax = a.y;
        }
        int width = xmax - xmin;
        int height = ymax - ymin;
        VGLViewport viewport = docViewPanel.getViewport();
        double aspect = (double)(viewport.xmax - viewport.xmin) / (double)(viewport.ymax - viewport.ymin);
        if (width > height) {
            height = (int)((double)width * aspect);
        }
        else {
            width = (int)((double)height / aspect);
        }
        if (a.x < b.x) {
            xmax = xmin + width;
        }
        else {
            xmin = xmax - width;
        }
        if (a.y < b.y) {
            ymax = ymin + height;
        }
        else {
            ymin = ymax - height;
        }
        return new VGLWindow(xmin, ymin, xmax, ymax);
    }

    private DocViewPanel docViewPanel;
    private Point downPoint;
    private Point dragPoint;
    private Point upPoint;
}
