/* Generated by Together */

package com.neocoders.vglviewer.vglViewer;

import com.neocoders.vglviewer.sdaz.SDAZDriver;
import java.awt.event.MouseEvent;
import com.neocoders.vglviewer.sdaz.SDAZPoint;
import java.awt.Point;

public class ListeningForSDAZMouse implements MouseHandler {
    public ListeningForSDAZMouse(SDAZDriver sdazDriver) {
        this.sdazDriver = sdazDriver;
    }

    public void mousePressed(MouseEvent e) {
        sdazDriver.notifyMouseDown(convertPoint(e.getPoint()));
    }

    public void mouseReleased(MouseEvent e) {
        sdazDriver.notifyMouseReleased(convertPoint(e.getPoint()));
    }

    public void mouseMoved(MouseEvent e) {
    }

    public void mouseDown(MouseEvent e) {
    }

    public void mouseUp(MouseEvent e) {
        sdazDriver.notifyMouseReleased(convertPoint(e.getPoint()));
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }

    public void mouseClicked(MouseEvent e) {
    }

    public void mouseDragged(MouseEvent e) {
        sdazDriver.notifyMouseDragged(convertPoint(e.getPoint()));
    }

    /** Converts an AWT Point into an SDAZPoint */
    private SDAZPoint convertPoint(Point p) {
        return new SDAZPoint(p.x, p.y);
    }

    private SDAZDriver sdazDriver;
}
