/* Generated by Together */

package com.neocoders.vglviewer.vglViewer;

import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

public interface MouseHandler extends MouseMotionListener, MouseListener {
}
