/* Generated by Together */

package com.neocoders.vglviewer.vglViewer;

import java.util.ArrayList;
import java.util.List;
import java.util.Iterator;
import com.neocoders.vglviewer.vglDocument.utils.ErrorHandler;

public class MultiErrorHandler implements ErrorHandler {
    public MultiErrorHandler() {
        errors = new ArrayList();
    }

    public void reset() {
        errors.clear();
    }

    public void handleError(String msg) {
        errors.add(msg);
    }

    public int getNumErrors() {
        return errors.size();
    }

    public Iterator getErrors() {
        return errors.iterator();
    }

    private List errors;
};

