/* Generated by Together */

package com.neocoders.vglviewer.vglViewer;

import com.neocoders.vglviewer.sdaz.SDAZWindow;
import com.neocoders.vglviewer.vglRenderer.VGLWindow;
import com.neocoders.vglviewer.sdaz.SDAZViewport;
import com.neocoders.vglviewer.vglRenderer.VGLViewport;
import com.neocoders.vglviewer.sdaz.SDAZSubject;
import com.neocoders.vglviewer.docViewPanel.DocViewPanel;


public class SDAZDocViewPanelSubject implements SDAZSubject {
    public SDAZDocViewPanelSubject(DocViewPanel panel) {
        this.docViewPanel= panel;
    }

    public SDAZWindow getWindow() {
        VGLWindow window = docViewPanel.getWindow();
        return new SDAZWindow(window.xmin, window.ymin, window.xmax, window.ymax);
    }

    public void setWindow(SDAZWindow w) {
        docViewPanel.setWindow(new VGLWindow(w.xmin, w.ymin, w.xmax, w.ymax));
    }

    public void update() {
        docViewPanel.repaint();
    }

    public void setIndicator(int x, int y, int width, int height) {
        /** Centre of map view panel */
        VGLWindow w = docViewPanel.getWindow();
        int xCentre = w.xmin + ((w.xmax - w.xmin) / 2);
        int yCentre = w.ymin + ((w.ymax - w.ymin) / 2);
        docViewPanel.setSDAZIndicator(xCentre, yCentre, xCentre + x, yCentre + y, width, height);
    }


    public SDAZViewport getViewport() {
        VGLViewport v = docViewPanel.getViewport();
        return new SDAZViewport(v.xmin, v.ymin, v.xmax, v.ymax);
    }

    public void setViewport(SDAZViewport viewport) {
        docViewPanel.setViewport(new VGLViewport(viewport.xmin, viewport.ymin, viewport.xmax, viewport.ymax));
    }

    /**
     * @supplierCardinality 1
     * @clientCardinality 1
     */
    private DocViewPanel docViewPanel;


}
